config/routes.rb
Lorious::Application.routes.draw do
  



  resources :transactions


  # basic public routes
  authenticated :user do
    root :to => 'users#dashboard'
  end
  
  get "/users/:id/dashboard" => "users#dashboard", as: "user_dashboard"
  get "/accounts" => "users#manage_payments", as: "manage_payments"
  get "/packages" => "home#credit_packages", as: "credit_packages"

  post "/packages/cart" => "credits#credits_cart", as: "credits_pre"

  post "/packages/card/buy" => "credits#buy_credits", as: "buy_credits"

  root :to => "home#audience_home"
  
  get 'blog_home' => "home#blog_home"
  get 'expert' => 'home#blog_home'
  get 'experts' => 'home#blog_home'
  get 'audience' => 'home#audience_home'
  get 'faq' => 'home#faq'
  get 'legal' => 'home#legal'

  get 'confirmed' => "home#confirmed"
  post 'confirmed' => "home#confirmed"

  resources :reviews
  resources :profiles
  resources :requests
  resources :charges
  resources :customers

  resources :services

  scope '/:user_id' do
    resources :appointments
    get "/appointments/:id/confirm" => "appointments#confirm", as: "confirm_appointment"
    resources :recipients
    resources :cards
    resources :credits
  end

  # devise_for :users #, :controllers => { :registrations => "registrations" } 
  devise_for :users, :controllers => { :registrations => "registrations", :omniauth_callbacks => "users/omniauth_callbacks" }
  resources :users
  devise_scope :user do
    get 'login' => "devise/sessions#new"
    get 'logout' => "devise/sessions#destroy"
    get 'signup' => "devise/registrations#new"
  end

  resources :conversations, only: [:index, :show, :new, :create] do
    member do
      post :reply
      post :trash
      post :untrash
    end
  end

  # chat routes
  get "chat/test" => "chat#test"
  # get 'chat/go/:user_id/:chat_key' => "chat#chat_prep"
  get 'chat/go/:chat_key/' => "chat#scheduled_chat", as: "chat_start"
  # get 'chat/go/:user_id/:chat_key/register' => "users#finish_registration"
  # get 'chat/go/:chat_key/error' => "home#error"
  get 'chat/go/:chat_key/end' => "chat#chat_end"

  # chat listener for determining conversation length
  post 'chat/report_listener' => "chat#report_listener"

  # custom signup routes for waiting list signup
  # put 'finish_pre_registration' => "users#edit_incomplete_registration"
  # post "profiles/pre" => "profiles#create_before_signup"
  # post "profiles/preup" => "profiles#update_before_signup"

  # authenticated :user do
  #  root :to => 'requests#index'
  # end

  # get 'message' => "home#message"
  # get '/:niche' => "home#audience_home"

  # user/profile show and edit routes
  get '/:id' => "users#show", as: "user_page"  
  get '/:id/avatar' => "users#upload_avatar", as: "avatar_page"
  get '/:id/expert' => "users#make_expert", as: "expert_approval"
  get '/:id/message' => "conversations#message", as: "message_user"
  # put '/avatars' => "users#update_avatar"

  


end

app/models/user.rb
class User < ActiveRecord::Base
  rolify

  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable, :authentication_keys => [:login]
  devise :omniauthable, :omniauth_providers => [:google_oauth2]

  after_create :assign_default_role, :create_profile

  # Setup accessible (or protected) attributes for your model
  attr_accessible :role_ids, :as => :admin
  attr_accessible :username, :login, :name, :email, :password, :password_confirmation, :remember_me, :avatar, :expert, :avatar_remote_url
  attr_accessible :stripe_customer_id, :stripe_recipient_id


  attr_accessor :login

  has_one :profile, dependent: :destroy
  has_one :card, dependent: :destroy
  # has_one :bank_account, dependent: :destroy

  has_many :services, :dependent => :destroy
  has_many :credits
  has_many :transactions

  has_one :profile, :dependent => :destroy
  has_one :card, dependent: :destroy
  has_one :bank_account, dependent: :destroy
  
  has_many :hosted_appointments, foreign_key: "host_id", class_name: "Appointment"
  has_many :appointments, foreign_key: "attendee_id"

  has_many :reviews, foreign_key: "reviewee_id"
  has_many :reviewed_users, foreign_key: "reviewer_id", class_name: "Review", dependent: :destroy

  # validate :check_avatar, if: "!avatar.blank?"

  # def check_avatar
  #   errors.add(:base, "Photo must be a JPG, PNG or GIF file") if !['image/jpeg', 'image/jpg', 'image/png', 'image/gif'].include?(avatar.content_type)
  #   errors.add(:base, "Photo must be less than 2 megabytes") if avatar.size > 2048
  # end

  # validates_attachment_presence :avatar unless :avatar.nil?
  validates_attachment_content_type :avatar, content_type: ['image/jpeg', 'image/jpg', 'image/png', 'image/gif'] unless :avatar.nil?
  validates_attachment_size :avatar, less_than: 2.megabytes, message: "Please upload a photo that is less than one megabyte." unless :avatar.nil?

  validates :username, presence: true, uniqueness: true
  validates :name, presence: true

  acts_as_messageable

  def mailboxer_email(object)
    #Check if an email should be sent for that object
    #if true
    return email
    #if false
    #return nil
  end

  extend FriendlyId
  friendly_id :username, use: [:slugged, :history]

  has_attached_file :avatar, styles: {
    thumb: '100x100>',
    square: '200x200#',
    medium: '300x300>'
  }, default_url: 'https://s3.amazonaws.com/lorious/layout/elements/placeholders/image_placeholder.jpg'


  def get_review_score
    reviews.average('rating').to_f
  end

# Credits Model
  def get_credits_total
    credits.sum('number').to_i
  end






  def avatar_remote_url=(url_value)
    url_value.gsub! /https/, 'http' unless url_value.blank?
    self.avatar = URI.parse(url_value) unless url_value.blank?
    # Assuming url_value is http://example.com/photos/face.png
    # avatar_file_name == "face.png"
    # avatar_content_type == "image/png"
    @avatar_remote_url = url_value
  end
  
  def self.find_first_by_auth_conditions(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions).where(["lower(username) = :value OR lower(email) = :value", { :value => login.downcase }]).first
    else
      where(conditions).first
    end
  end

  ### This is the correct method you override with the code above
  ### def self.find_for_database_authentication(warden_conditions)
  ### end 

  def self.find_for_google_oauth2(access_token, signed_in_resource=nil)
    data = access_token.info
    user = User.where(:email => data["email"]).first

    # print access_token.to_yaml
    # print data

    unless user
        user = User.create(name: data["name"],
             username: Devise.friendly_token[0,5],
             email: data["email"],
             password: Devise.friendly_token[0,20],
             avatar_remote_url: access_token["info"]["image"]
            )
        # Add Google Service (required)
        user.services.create(provider: access_token["provider"], uid: access_token["uid"], uname: access_token["info"]["name"], uemail: access_token["info"]["email"])
    end
    user
  end

  def first_name
    name.split[0]
  end

  def short_name
    unless name.split[1][0].nil?
      name.split[0] + " " + name.split[1][0] + "."
    else
      first_name
    end
  end


  protected


  # def confirmation_required?
  #   false
  # end

  def assign_default_role
    # Default Role: User, ID: 2
    add_role(:user)
  end

  def create_profile
    profile = Profile.new
    profile.user = self
    profile.fname = profile.first_name
    profile.lname = profile.last_name
    profile.display_name = profile.public_name
    profile.save

  end
  
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def google_oauth2
      # You need to implement the method below in your model (e.g. app/models/user.rb)
      @user = User.find_for_google_oauth2(request.env["omniauth.auth"], current_user)

      if @user.persisted?
        flash[:notice] = I18n.t "devise.omniauth_callbacks.success", :kind => "Google"
        sign_in_and_redirect @user, :event => :authentication
      else
        session["devise.google_data"] = request.env["omniauth.auth"]
        redirect_to new_user_registration_url
      end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # before_filter :authenticate_user!, except: [:update, :show, :finish_registration, :edit_incomplete_registration]
  load_and_authorize_resource

  def dashboard
    @user = current_user

    @appointments = Appointment.find(:all, conditions: ['host_id = ? OR attendee_id = ?', @user.id, @user.id])

  end

  def manage_payments
    @user = current_user
    @card_on_file = false
    @bank_account_on_file = false
    
    if !@user.stripe_customer_id.nil?
      customer = Stripe::Customer.retrieve(@user.stripe_customer_id)
      card = customer.cards.retrieve(@user.card.stripe_card_id)
      @card_type = card["type"]
      @card_on_file = true
    end

    if !@user.stripe_recipient_id.nil?
      recipient = Stripe::Recipient.retrieve(@user.stripe_recipient_id)

      bank_account = recipient.active_account

      @bank_account_type = bank_account.bank_name
      @bank_account_on_file = true
    end

  end

  # def finish_registration
  #   #authorize! :finish_registration, :users
  #   @user_id = params[:user_id]
  #   @chat_key = params[:chat_key]

  #   @user = User.find_by_id(@user_id)

  #   @appointment = Appointment.find_by_chat_key(@chat_key)

  #   if @user != @appointment.try(:host) && @user != @appointment.try(:attendee)
      
  #     @destination = "/chat/go/" + @user_id.to_s + @chat_key + "/error"

  #     redirect_to @destination
  #   end
  # end


  # def edit_incomplete_registration
  #   authorize! :edit_incomplete_registration, :users
  #   @user_id = current_user.id
  #   @user_id ||= params[:user][:id]
    
  #   @chat_key = params[:user][:chat_key]
  #   @user = User.find_by_id(@user_id)
    
  #   @user.password = params[:user][:password]
  #   @user.password_confirmation = params[:user][:password_confirmation]
  #   @user.fully_registered = true
  #   @user.save

  #   @destination = "/chat/go/" + @user_id.to_s + "/" + @chat_key

  #   redirect_to @destination

  # end

  def index
    # authorize! :index, @user, :message => 'Not authorized as an administrator.'
    @users = User.all
  end

  def show
    # authorize! :show, @user, :message => 'Not authorized as an administrator'
    @user_id = params[:id]
    @user_id ||= current_user.id

    @user = User.find(@user_id)
    @profile = @user.profile


    if @user.profile == nil
      @display = "none"
    else
    # for now, make @display always = all for dev; later, will allow user to set privacy

    @display = "all"
    end

    # if @user.profile.privacy == "private" && current_user != @user.id
    #   @display = "none"
    # else
    #   @display = "all"
    # end
  end
  
  def update
    #authorize! :update, @user, :message => 'Not authorized as an administrator.'
    
    @user = User.find(params[:id]) || current_user
    @profile = @user.profile
    if current_user.has_role? :admin
      if @user.update_attributes(params[:user], as: :admin)
        redirect_to users_path, :notice => "User updated."
      else
        redirect_to users_path, :alert => "Unable to update user."
      end
    else
      if @user.update_attributes(params[:user])
        redirect_to @user, :notice => "User updated."
      else
        # flash[:error] = @user.errors.to_a
        redirect_to @user, :alert => "Unable to update user."
      end
    end
  end
    
  def destroy
    authorize! :destroy, @user, :message => 'Not authorized as an administrator.'
    user = User.find(params[:id])
    unless user == current_user
      user.destroy
      redirect_to users_path, :notice => "User deleted."
    else
      redirect_to users_path, :notice => "Can't delete yourself."
    end
  end

  # def update_avatar
  #   #authorize! :update, @user, :message => 'Not authorized as an administrator.'
    
  #   @user = User.find(params[:id]) unless params[:id].blank?
  #   @user ||= current_user
  #   @profile = @user.profile
  #   if current_user.has_role? :admin
  #     if @user.update_attributes(params[:user], as: :admin)
  #       redirect_to users_path, :notice => "User updated."
  #     else
  #       redirect_to users_path, :alert => "Unable to update user."
  #     end
  #   else
  #     if @user.update_attributes(params[:user])
  #       redirect_to @user, :notice => "User updated."
  #     else
  #       render action: upload_avatar, :messages => @user.errors.to_a || "Unable to update user."
  #     end
  #   end
  # end


  def upload_avatar
    @action = params[:action]
    render "edit"
  end
  def make_expert
    authorize! :expert, @user, :message => 'Not authorized as an administrator.'
    @action = params[:action]
    render "edit"
  end

  private

end

app/views/users/_addpassword.html.haml
= simple_form_for @user, url: finish_pre_registration_path, method: :put, html: {id: "signup"}  do |f|
  = f.error_notification

  .form-inputs
    = f.input :password, input_html: { class: "required", placeholder: "Create Password", id: "password" }
    = f.input :password_confirmation, input_html: { class: "required", placeholder: "Confirm Password", id: "password_confirm" }
    = f.input :id, as: :hidden, input_html: { value: @user.id }
    = f.input :chat_key, as: :hidden, input_html: { value: @chat_key }

  .form-actions
    = f.button :submit

app/views/users/_make_expert.html.haml
.row-fluid
  .container-fluid#profile
    .span6.offset2.centered
      %br
      %br
      = simple_form_for(@user, html: { class: "form-vertical"}) do |f|
        = f.error_notification
        = f.input :expert, label: "User is an Expert?"
        .form-buttons
          = f.button :submit, "Change Expert Setting", class: "button"

app/views/users/_upload_avatar.html.haml
.row-fluid
  .container-fluid
    .span6.offset2.centered
      %p.strong Current Picture:
      %br
      =image_tag @user.avatar.url(:square), class: "user-profile-image"
      %br
      %br
      = simple_form_for(@user, html: { class: "form-horizontal"}) do |f|
        = f.error_notification
        = f.full_error :image_file_size, class: "alert alert-error" 
        = f.full_error :image_content_type, class: "alert alert-error"

        = f.input :avatar, label: false
        .form-buttons
          = f.button :submit, "Update Picture", class: "button"
        %p.muted Photo must be a JPG, PNG or GIF file and less than 2 megabytes.

app/views/users/_user.html.haml
.modal{:id => "role-options-#{user.id}", :style => "display: none;"}
  = simple_form_for user, :url => user_path(user), :html => {:method => :put, :class => 'form-horizontal' } do |f|
    .modal-header
      %a.close{"data-dismiss" => "modal"} ×
      %h3 Change Role
    .modal-body
      = f.input :role_ids, :collection => Role.all, :as => :radio_buttons, :label_method => lambda {|t| t.name.titleize}, :label => false, :item_wrapper_class => 'inline', checked: user.role_ids.first
    .modal-footer
      = f.submit "Change Role", :class => "btn"
      %a.btn{"data-dismiss" => "modal", :href => "#"} Close

.modal{:id => "expert-options-#{user.id}", :style => "display: none;"}
  = simple_form_for user, :url => user_path(user), :html => {:method => :put, :class => 'form-horizontal' } do |f|
    .modal-header
      %a.close{"data-dismiss" => "modal"} ×
      %h3 Make User an Expert?
    .modal-body
      = f.input :expert, :collection => [true, false], :as => :radio_buttons, :item_wrapper_class => 'inline', checked: user.expert
    .modal-footer
      = f.submit "Change Whether Expert", :class => "btn"
      %a.btn{"data-dismiss" => "modal", :href => "#"} Close

app/views/users/dashboard.html.haml
%section.row-fluid.dashboard-overview
  .max-container
    .span8.offset2
      %h2 User Dashboard
      %p
        You are logged in as
        =@user.name
        ="(" + @user.email + ")"
%section.row-fluid.dashboard-options
  .span8.offset2
    .max-container
      %ul
        %li= link_to "Edit User Information", edit_user_registration_path(current_user)
        %li
          -unless @user.profile
            = link_to "Create A Profile", new_profile_url
          -else
            = link_to "View/Edit Your Profile", user_page_path(@user.slug)
        %li Manage Privacy Settings 
        %li Manage Upcoming Appointments
        -if !@user.expert
          %li 
            Apply to Be an Expert
        -elsif @user.expert
          %li
            Manage Availability for Appointments
            /   = link_to "Apply to be an expert", current_user
        %li= link_to "Manage Payment Options", manage_payments_path
        %li= link_to "Inbox", conversations_path
        %li
          = link_to "Buy Credits", credit_packages_path


%section.row-fluid.dashboard-appointments
  .span8.offset2
    .max-container
      %h3 Listing Appointments
      %table.table
        %tr
          %th Host
          %th Attendee
          %th Time (EST)
          %th URL
          %th
          %th
        =render @appointments unless @appointments.nil?

app/views/users/edit.html.haml
- content_for :main_content do
  -if @action=="upload_avatar"
    =render 'upload_avatar'
  -if @action=="make_expert"
    =render 'make_expert'

app/views/users/finish_registration.html.haml
:javascript
  $(document).ready(function(){
  $('#signup').validate({
      rules: {
          "user[password]": {
            required: true, minlength: 8
          },
          "user[password_confirmation]": {
            required: true, minlength: 8, equalTo: "#password"
          }
      
      },
      messages: {
        "user[password]": {
            required: "Please provide a password",
            minlength: "Your password must be at least 8 characters long"
        },
        "user[password_confirmation]": {
            required: "Please provide a password",
            minlength: "Your password must be at least 8 characters long",
            equalTo: "Please enter the same password as above"
        }
    }
  });
     });

%h3 Finish Registration
%well
  =render "addpassword"

app/views/users/index.html.haml
%h3 Users
.row-fluid
  .span8
    %table.table.table-condensed
      %thead
        %tr
          %th Username
          %th Email
          %th Registered
          %th Expert
          %th
          %th Role
          %th
          %th
      %tbody
        - @users.each do |user|
          %tr
            %td= link_to user.name, user
            %td= user.email
            %td= user.created_at.to_date
            %td= user.expert
            %td
              %a.btn.btn-mini{"data-toggle" => "modal", :href => "#expert-options-#{user.id}", :type => "button"} Make Expert?
              = render user
            %td= user.roles.first.name.titleize unless user.roles.first.nil?
            %td
              %a.btn.btn-mini{"data-toggle" => "modal", :href => "#role-options-#{user.id}", :type => "button"} Change role
              = render user
            %td= link_to("Delete user", user_path(user), :data => { :confirm => "Are you sure?" }, :method => :delete, :class => 'btn btn-mini') unless user == current_user

app/views/users/manage_payments.html.haml
%section.row-fluid.manage-payments-overview
  %h2 Manage Payment Accounts
  %p.muted
    In order to meet with a teacher, you must put a credit card on file. Your card will be charged when you schedule an appointment. The payment will be held until you confirm you had a successful interaction with your teacher.
  %p.muted
    In order to host an appointment and accept payment, you must put a bank account on file. You will be paid once you have accrued $50 or more in fees.
%section.row-fluid.manage-payments-details
  %ul.unstyled
    -if @card_on_file
      %li.strong
        %i.icon-ok
        = "Card Added! (" + @card_type + ") "
        =link_to "Manage Card", cards_path(id: current_user.id)
        %p.muted You're ready to schedule appointments and make payments!
    -else
      %li.strong
        %i.icon-remove
        No Card on File 
        = link_to "Add Card", cards_path(id: current_user.id)
    %br
    %br
    -if @bank_account_on_file
      %li.strong
        %i.icon-ok
        = "Bank Account Added! (" + @bank_account_type + ") "
        =link_to "Manage Bank Account", recipients_path(id: current_user.id)
        %p.muted You're ready to host appointments and accept payments!
    -else
      %li.strong
        %i.icon-remove
        No Bank Account on File
        =link_to "Add Bank Account", recipients_path(id: current_user.id)

    %br
    %br

    =link_to "Back to Dashboard", user_dashboard_path(current_user)

app/views/users/show.html.haml
- content_for :head do
  - if @profile.user.hosted_appointments.count > 0
    :javascript
      $(function() {
        $('#star-average').raty({ readOnly: true, score: #{@profile.user.get_review_score} });
      });
  -@profile.user.reviews.each do |review|
    :javascript
      $(function() {
        $('#star#{review.id}').raty({ readOnly: true, score: #{review.rating} });
      });
- content_for :main_content do
  -if @display == "none"
    %h6.alert This user has not made their profile public.
  -elsif @display == "all"
    / %ul.profile-nav-band
    /   -if current_user 
    /     %li.profile-nav-band-link
    /       = link_to "Edit Profile", edit_profile_url(Profile.find_by_user_id(current_user.id))
    /     %li.profile-nav-band-link
    /       = link_to "User Profile", current_user
    /   -else
    /     %li.profile-nav-band-link
    /       = link_to "Book An Appointment with #{@profile.user.name}", current_user
    /     %li.profile-nav-band-link
    /       = link_to "#{@profile.user.name.split.first.pluralize} reviews", current_user
    /     %li.profile-nav-band-link
    /       = link_to "Ask #{@profile.user.name.split.first} a question", current_user
    / %h3 User
    / %p
    /   User: #{@user.profile.public_name}
    / %p
    /   Picture: 
    /   =image_tag @user.avatar.url(:square), class: "user-profile-image"
    / %p
    /   Tagline: #{@user.profile.tagline}
    / %p
    /   Bio: #{@user.profile.bio}
    / %p
    /   Reviews:
    /   - @user.reviews.each do | review |
    /     %br
    /     = review.rating
    /     = review.content
    /     = "from " + review.reviewer.profile.public_name
    /   %br
    /   Average Score:
    /   = @user.get_review_score
    / .navbar.navbar-inverse
    /   .navbar-inner
    /     .container

    /       %a.btn.btn-navbar{"data-target" => ".nav-collapse", "data-toggle" => "collapse"}
    /         %span.icon-bar
    /         %span.icon-bar
    /         %span.icon-bar
    /     .nav-collapse.collapse
    /       %ul.nav
    /         %li 
    /           %a{href: "#"} Test
    /         %li 
    /           %a{href: "#"} Test 2
    /         %li 
    /           %a{href: "#"} Test 3




    / .row-fluid.profile-nav-band
    /   .span10
    /     .max-container
    /       %ul
    /         %li.profile-nav-band-link
    /           = link_to "User Profile", current_user
    /         %li.profile-nav-band-link
    /           = link_to "Book An Appointment with #{@profile.name}"
    /         %li.profile-nav-band-link
    /           = link_to "#{@profile.user.name.split.first.pluralize} reviews"
    /         %li.profile-nav-band-link
    /           = link_to "Ask #{@profile.user.name.split.first} a question"
    /   %span#notice= notice

    / Needed links: edit profile info, edit avatar
    -if can? :edit, @profile
      .row-fluid
        .span9.offset1
          %br
          = link_to "Edit Profile", edit_profile_url(Profile.find_by_user_id(current_user.id))
    .row-fluid
      .container-fluid#profile
        .span9
          .profile-overview-left
            .picture-rating-consultations
              .name-and-headline
                .img-div
                  =image_tag @user.avatar.url(:square), class: "user-profile-image img-polaroid"
                  %br
                  -if can? :edit, @profile
                    -if @profile.user.avatar
                      =link_to "Edit Picture", avatar_page_url(@user.slug)
                    -else
                      =link_to "Add Picture", avatar_page_url(@user.slug)
                .text
                  %h2
                    = @user.short_name
                  %p
                    = @profile.tagline

                    %br
                    - if @profile.user.hosted_appointments.count > 0
                      %p
                        %span.strong 
                          Experience
                      = @profile.user.hosted_appointments.count
                      Hosted
                      ="Appointment".pluralize(@profile.user.hosted_appointments.count)
                      %br
                      Average Rating:
                      %br
                      .star{id: "star-average"}
                      

        -if @user.expert
          .span3.price-and-booking
            .price-and-booking
              .price-box
                %p.strong Price/hour
                %p= number_to_currency(@profile.expertise_hourly, precision: 0) || "Email to ask"
                %br
                %br
                = link_to "Request appointment with #{@user.short_name}", new_appointment_path(@user)
                %br
                -if @profile.user != current_user
                  =link_to "Contact #{@user.short_name}", message_user_path(@profile.user.slug)

    .row-fluid.profile-expert-information
      .container-fluid#profile
        .span12
          %h2 Talk To Me About:
          %p= simple_format(@profile.bio) || "User has not shared any information yet"
    .row-fluid
      .container-fluid#profile.profile-reviews
        .span12
          -if @profile.user.reviews.count > 0
            %h2 
              ="Reviews (" + @profile.user.reviews.count.to_s + ")"
          %ul.profile-reviews-list
            - @profile.user.reviews.each do |review| 
              %li.profile-review
                %h3
                  = review.reviewer.short_name
                  says
                %p= review.content
                %p.strong
                  .star{id: "star#{review.id}"}
            / %li.profile-review
            /   %h3 Roneesh says...
            /   %p Jake Welchert is a pretty good designer and I think he gave me a lot of valid information.
            /   #star
            / %li.profile-review
            /   %h3 Roneesh says...
            /   %p Jake Welchert is a pretty good designer and I think he gave me a lot of valid information.
            /   %p.strong 4.0 / 5.0
            / %li.profile-review
            /   %h3 Roneesh says...
            /   %p Jake Welchert is a pretty good designer and I think he gave me a lot of valid information.
            /   %p.strong 4.0 / 5.0
        

app/views/users/upload_avatar.html.haml
.row-fluid
  .container-fluid
    .span6.offset2.centered
      %p.strong Current Picture:
      %br
      =image_tag @user.avatar.url(:square), class: "user-profile-image"
      %br
      %br
      = simple_form_for(@user, html: { class: "form-horizontal"}) do |f|
        = f.error_notification
        = f.full_error :image_file_size, class: "alert alert-error" 
        = f.full_error :image_content_type, class: "alert alert-error"

        = f.input :avatar, label: false
        .form-buttons
          = f.button :submit, "Update Picture", class: "button"
        %p.muted Photo must be a JPG, PNG or GIF file and less than 2 megabytes.