config/routes.rb
Lorious::Application.routes.draw do
  



  resources :transactions


  # basic public routes
  authenticated :user do
    root :to => 'users#dashboard'
  end
  
  get "/users/:id/dashboard" => "users#dashboard", as: "user_dashboard"
  get "/accounts" => "users#manage_payments", as: "manage_payments"
  get "/packages" => "home#credit_packages", as: "credit_packages"

  post "/packages/cart" => "credits#credits_cart", as: "credits_pre"

  post "/packages/card/buy" => "credits#buy_credits", as: "buy_credits"

  root :to => "home#audience_home"
  
  get 'blog_home' => "home#blog_home"
  get 'expert' => 'home#blog_home'
  get 'experts' => 'home#blog_home'
  get 'audience' => 'home#audience_home'
  get 'faq' => 'home#faq'
  get 'legal' => 'home#legal'

  get 'confirmed' => "home#confirmed"
  post 'confirmed' => "home#confirmed"

  resources :reviews
  resources :profiles
  resources :requests
  resources :charges
  resources :customers

  resources :services

  scope '/:user_id' do
    resources :appointments
    get "/appointments/:id/confirm" => "appointments#confirm", as: "confirm_appointment"
    resources :recipients
    resources :cards
    resources :credits
  end

  # devise_for :users #, :controllers => { :registrations => "registrations" } 
  devise_for :users, :controllers => { :registrations => "registrations", :omniauth_callbacks => "users/omniauth_callbacks" }
  resources :users
  devise_scope :user do
    get 'login' => "devise/sessions#new"
    get 'logout' => "devise/sessions#destroy"
    get 'signup' => "devise/registrations#new"
  end

  resources :conversations, only: [:index, :show, :new, :create] do
    member do
      post :reply
      post :trash
      post :untrash
    end
  end

  # chat routes
  get "chat/test" => "chat#test"
  # get 'chat/go/:user_id/:chat_key' => "chat#chat_prep"
  get 'chat/go/:chat_key/' => "chat#scheduled_chat", as: "chat_start"
  # get 'chat/go/:user_id/:chat_key/register' => "users#finish_registration"
  # get 'chat/go/:chat_key/error' => "home#error"
  get 'chat/go/:chat_key/end' => "chat#chat_end"

  # chat listener for determining conversation length
  post 'chat/report_listener' => "chat#report_listener"

  # custom signup routes for waiting list signup
  # put 'finish_pre_registration' => "users#edit_incomplete_registration"
  # post "profiles/pre" => "profiles#create_before_signup"
  # post "profiles/preup" => "profiles#update_before_signup"

  # authenticated :user do
  #  root :to => 'requests#index'
  # end

  # get 'message' => "home#message"
  # get '/:niche' => "home#audience_home"

  # user/profile show and edit routes
  get '/:id' => "users#show", as: "user_page"  
  get '/:id/avatar' => "users#upload_avatar", as: "avatar_page"
  get '/:id/expert' => "users#make_expert", as: "expert_approval"
  get '/:id/message' => "conversations#message", as: "message_user"
  # put '/avatars' => "users#update_avatar"

  


end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    # @users = User.all
  end

  def audience_home
    @action = params[:action]
    @disable_header = true
    @profile = Profile.new
    @niche = params[:niche] || "crafting"


    case @niche
    when "crafting"
      @headline = "Your central place for crafting help"
    else
      @headline = "Welcome to Lorious!"
    end

  end

  def blog_home
    @action = params[:action]
    @disable_header = true
    @profile = Profile.new
    @niche = params[:niche] || "blogging"


    case @niche
    when "blogging"
      @headline = "Engage your audience through video."
    else
      @headline = "Welcome to Lorious!"
    end
  end

  def credit_packages
    @credit = Credit.new
  end

  def faq

  end

  def more
    @email = session[:email]
    @profile = Profile.find_by_email(@email)
    @request = Request.new

    case @profile.niche
    when "crafting"
      @sample_expertise = "knitting, decorating, terrariums"
      @sample_interest = "jewelry, painting, design"
    else
      @sample_expertise = "anything!"
      @sample_interest = "anything!"
    end
      
  end

  # def thanks

  # end

  def confirmed
    
    add_to_list_niche(params[:waiting_list_signup][:fname], params[:waiting_list_signup][:email], params[:waiting_list_signup][:niche], list_id=ENV["MAILCHIMP_LISTID"])
    
    if params[:waiting_list_signup][:user_type] == "expert"
      update_list_subscription(params[:waiting_list_signup][:email], "EXPERT", "true", list_id=ENV["MAILCHIMP_LISTID"])
    elsif params[:waiting_list_signup][:user_type] == "user"
      update_list_subscription(params[:waiting_list_signup][:email], "USER", "true", list_id=ENV["MAILCHIMP_LISTID"])
    end

    # if session[:new_profile] == true
    #   @profile = Profile.find_by_email(session[:email])
      # send_mail("Henry from Lorious", "henry@lorious.com", 
      #   @profile.name, 
      #   session[:email], 
      #   "Lorious | #{@profile.fname} - Welcome to Lorious!", 
      #   "Hi #{@profile.fname},
      #   \r\nThank you for signing up for Lorious! We can't wait to start connecting you to our community.
      #   \r\nLorious is an online marketplace for knowledge and expertise. People like you turn to Lorious in search of experts for advice, to solve a problem or to learn a new skill. We hope to help you and all of our users grow and succeed by giving you convenient access via to the experts you need.
      #   \r\nWe hope you will be one of the first members of our community, which will start as an exclusive group of people committed to learning and helping others to learn. Your feedback will be incredibly valuable in shaping our ability to help our community succeed.
      #   \r\nWe'll get back to you as soon as we possibly can so we can get started with helping you tackle your challenges.
      #   \r\nSincerely,
      #   \r\nHenry, co-founder, http://www.lorious.com")

  end

  def error
    @referer = request.env['HTTP_REFERER']
    @uri = request.env['REQUEST_URI']
    send_mail("Errors @ Lorious", "admin@lorious.com", "Team", "admin@lorious.com", "Lorious ADMIN | Error Reported", "Error reported\r\n\r\nPage: #{@uri}\r\n\r\nPage: #{@referer}")
    redirect_to "/"
  end

  def message
    # send_mail(from_name, from_email, to_name, to_email, subject, *content)
    # content[0]=text, content[1]=html (optional)
    # send_mail("Henry", 
    #           "henry@xxx", 
    #           "Hank", 
    #           "hhund@xxx", 
    #           "Test message", 
    #           "text", 
    #           "<h3>but I prefer HTML</h3>")

    # add_to_list("Hank","henry@lorious.com")
  end

  def legal

  end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/audience_home.html.haml
/javascript for validation
:javascript
  $(document).ready(function(){
  $('#signup').validate({
      rules: {
          fname: "required",
          email: "email",
      
      },
      messages: {
          fname: "Your name is required",
          email: "Your email is required",
      },
      errorContainer: $('#errorContainer'),
      errorLabelContainer: $('#errorContainer ul'),
      wrapper: 'li'
  });
    });

/ %section.row-fluid.landing-upper-nav
/   .span6.logo
/     %a{href: "/"}
/       =image_tag "https://s3.amazonaws.com/lorious/layout/lorious_white.svg", width: "100px"
/   .span6.nav
/     %ul
/       %li= link_to "Be an Expert", expert_path
/       %li= mail_to "questions@lorious.com", "Contact Us"

%section.row-fluid.hero.hero-landing-page
  .container-fluid
    .span12
      %h2 Learn from the best
      %p Private lessons and consultations from experienced experts who&#39;ve been through it. Whatever your challenge, we connect you with someone who can teach you what you need to know &#8211; anywhere, anytime.
      %a(href="#help-us-out")
        %span.button Sign up

%section.row-fluid.how-it-works
  .container-fluid
    .span6.landing-left
      %h1 How it works...
      %p Lorious puts you in touch with experts so you can get face-to-face instruction online, tailored to your&nbsp;questions
    .span6.landing-right
      %ul
        %li
          .number
            =image_tag "https://s3.amazonaws.com/lorious/layout/elements/landing_page/1.svg", width: "80px"
          .copy
            %h3 Find the perfect expert
            %p Access our community and find the right person to help you. Fees may vary by expert.
        %li
          .number
            =image_tag "https://s3.amazonaws.com/lorious/layout/elements/landing_page/2.svg", width: "80px"
          .copy
            %h3 Get in touch
            %p Work with someone instantly or schedule a conversation at a convenient time
        %li
          .number
            =image_tag "https://s3.amazonaws.com/lorious/layout/elements/landing_page/3.svg", width: "80px"
          .copy
            %h3 Connect and videochat
            %p Talk for 5 minutes or 5 hours, until you&#39;ve gotten the help you need

%section.row-fluid.help-us-out#help-us-out
  .container-fluid
    .span6.landing-left
      %h1 Request an invitation
      %p We&#39;re currently in private beta mode. Please sign up for an invite. 
      
    .span6.landing-right
      = simple_form_for :waiting_list_signup, url: confirmed_path, method: :post, html: {id: "signup"} do |f|
        = f.error_notification

        .form-inputs
          = f.input :fname, label: false, input_html: {placeholder: "Your first name", id: "fname"}
          = f.input :email, label: false, input_html: {placeholder: "Your email", id: "email"}
          = f.input :niche, input_html: {value: @niche}, as: :hidden
          = f.input :user_type, input_html: {value: "user"}, as: :hidden
          
        = f.button :submit, "Request an Invitation", class: "button"

app/views/home/blog_home.haml
/javascript for validation
:javascript
  $(document).ready(function(){
  $('#signup').validate({
      rules: {
          fname: "required",
          email: "email",
      
      },
      messages: {
          fname: "Your name is required",
          email: "Your email is required",
      },
      errorContainer: $('#errorContainer'),
      errorLabelContainer: $('#errorContainer ul'),
      wrapper: 'li'
  });
    });

%section.row-fluid.landing-upper-nav
  .span6.logo
    %a{href: "/"}
      =image_tag "https://s3.amazonaws.com/lorious/layout/lorious_white.svg", width: "100px"
  .span6.nav
    %ul
      %li= link_to "Not an Expert?", root_path
      %li= mail_to "questions@lorious.com", "Contact Us"
/ %section.row-fluid.landing-upper-nav
/   .span2.logo
/     %a{href: "/"}
/       =image_tag "https://s3.amazonaws.com/lorious/layout/lorious_white.svg", width: "100px"
/   .span10.nav
/     %ul
/       %li= link_to "Not an Expert?", root_path
/       %li= mail_to "questions@lorious.com", "Contact Us"

%section.row-fluid.hero.hero-landing-page
  .container-fluid
    .span12
      %h2 We Want To Help You Get More From Your Audience
      %p We're building a platform to help content creators like you offer private consultations through videochat. All you have to do is set your rates and tell your audience you're there to help - we'll handle the rest. 
      %a(href="#blog-signup")
        %span.button Sign up

%section.row-fluid
  .container-fluid
    %h1.benefit-header Benefits for you
    %ul.benefits-list.clearfix
      %li.benefit
        %h3 A new way to monetize
        %p You've already proven you're an expert. Help people one-on-one and charge the rates you want for each conversation.
      %li.benefit
        %h3 Talk at your convenience
        %p Set your own schedule, talk only when you have the time.
      %li.benefit
        %h3 Increase your exposure
        %p We want to help you grow. Not only will you have access to your audience, you'll have access to ours too.

%section.row-fluid.blog-landing-signup#blog-signup
  .container-fluid
    .span6.offset2.landing-left
      %h1 Request an invitation
      %p We're currently in private beta mode.
      %p Sign up to request an invite.
    .span4.landing-right
      = simple_form_for :waiting_list_signup, url: confirmed_path, method: :post, html: {id: "signup"} do |f|
        = f.error_notification

        .form-inputs
          = f.input :fname, label: false, input_html: {placeholder: "Your first name", id: "fname"}
          = f.input :email, label: false, input_html: {placeholder: "Your email", id: "email"}
          = f.input :niche, input_html: {value: @niche}, as: :hidden
          = f.input :user_type, input_html: {value: "expert"}, as: :hidden
          
        = f.button :submit, "Sign Up", class: "button"

app/views/home/confirmed.html.haml
.row-fluid
  .span10.offset1{style:"text-align:center;"}
    %br
    %br
    %h2.large-header{style:"padding-bottom:25px;"} Thanks! We'll be in touch with you soon!
    %p.text If you're excited about what we're doing, please help us out by sharing with your friends! Like us on Facebook and follow us on Twitter!
.row-fluid.big-social-links
  .span6
    %a{href: "https://www.facebook.com/pages/Lorious/357664217669583", target: "_blank"}
      =image_tag "https://s3.amazonaws.com/lorious/layout/elements/social/facebook_green_icon.svg", width: "60%"
  .span6
    %a{href: "https://twitter.com/intent/user?screen_name=LoriousTweets", target:"_blank"}
      =image_tag "https://s3.amazonaws.com/lorious/layout/elements/social/twitter_green_icon.svg", width: "60%"

app/views/home/credit_packages.html.haml
.row-fluid
  .span10.offset1
    %h2 Lorious Credit Packages
    .span3
      .well
        %h2.muted Silver
        %p
          %span.label POPULAR
        %ul
          %li Buy Credits in bulk!

        %p Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nisi. Nulla quis sem at nibh elementum imperdiet. Duis sagittis ipsum. Praesent mauris. Fusce nec tellus sed augue semper porta.
        %hr/
        %h3 $25
        %hr/
        %p
        = simple_form_for(@credit, url: credits_pre_path) do |f|
          = f.error_notification

          .form-inputs
            = f.input :user_id, as: :hidden, input_html: { value: current_user.id}
            = f.input :number, as: :hidden, input_html: { value: 25 }

          .form-actions
            = button_tag(type: 'submit', class: "btn btn-large") do
              %i.icon-ok 
              Buy 25 Credits
    .span3
      .well
        %h2.text-warning Bronze
        %p
          %span.label.label-success POPULAR
        %ul
          %li Buy Credits in bulk!

        %p Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nisi. Nulla quis sem at nibh elementum imperdiet. Duis sagittis ipsum. Praesent mauris. Fusce nec tellus sed augue semper porta.
        %hr/
        %h3 $100
        %hr/
        %p
        = simple_form_for(@credit, url: credits_pre_path) do |f|
          = f.error_notification

          .form-inputs
            = f.input :user_id, as: :hidden, input_html: { value: current_user.id}
            = f.input :number, as: :hidden, input_html: { value: 100 }

          .form-actions
            = button_tag(type: 'submit', class: "btn btn-large") do
              %i.icon-ok 
              Buy 100 Credits

    .span3
      .well
        %h2.text-info Economy
        %p
          %span.label.label-info BUDGET
        %ul
          %li Buy Credits in bulk!
        %p Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nisi. Nulla quis sem at nibh elementum imperdiet. Duis sagittis ipsum. Praesent mauris. Fusce nec tellus sed augue semper porta.
        %hr/
        %h3 $250
        %hr/
        %p
        = simple_form_for(@credit, url: credits_pre_path) do |f|
          = f.error_notification

          .form-inputs
            = f.input :user_id, as: :hidden, input_html: { value: current_user.id}
            = f.input :number, as: :hidden, input_html: { value: 250 }

          .form-actions
            = button_tag(type: 'submit', class: "btn btn-large") do
              %i.icon-ok 
              Buy 250 Credits

app/views/home/faq.html.haml
.row-fluid
  .span10.offset1
    %br
    %br
    %h2.large-header FAQ - Lorious Beta

    %p.text 
      Thank you for signing up for the Lorious beta! We&#39;re really excited that you&#39;re joining our community. We&#39;re still working on making the site perfect for our users but we&#39;re so excited about what we&#39;re doing that we couldn&#39;t wait to start sharing it with you.  

    %p.text 
      We&#39;ve had a lot of questions from you and we wanted to share some answers about how our beta works. 

    %p.text
      Please send any additional questions or comments you have to 
      %a{href:"mailto:questions@lorious.com" } questions@lorious.com.
      As one of our first members, your feedback will be invaluable in helping us grow and shape our community. We can&#39;t wait to hear from you!

    %br

    %h2.large-header About Lorious

    %h3.question-header What is Lorious?

    %p.text
      Lorious is an online marketplace for expertise and knowledge. Our community turns to Lorious in search of experts for advice, to solve a problem or to learn a new skill. We provide a direct and personal connection via live video chat with the experts that you need.

    %p.text
      We at Lorious believe in empowering everyone to take the steps they need to grow and succeed. We want users to have the help they need to acquire new skills and knowledge. We want experts to have a platform to share what they know with the world and make some money doing so. We believe in a more personalized approach to learning, and we believe in your potential. 


    %h3.question-header Why should I use Lorious?

    %p.text 
      We know there are a lot of ways to learn on the internet, but the process often involves hours of digging to find the one piece of information you need. We&#39;ve all been there - sometimes you&#39;re stuck and before you know it you&#39;ve spent 3 hours (or worse, 3 days) on Google and are no closer to a solution.

    %p.text
      At Lorious, we believe that there&#39;s a better way to get answers. A more personal way. We want to put you in touch with someone who can help, someone who has the specific expertise you need, so that you can get the right advice when you need it, wherever you are. Whether you have specific problems or just want to fast-track  your learning, Lorious can help.


    %h3.question-header Is it free to join?

    %p.text
      Lorious does not charge anything to sign up and join our community. The only time you may have to pay is if you have a conversation with an expert who charges a particular rate (some experts may be willing to speak for free). 

    %h3.question-header What&#39;s the best browser to use with Lorious?

    %p.text 
      Lorious uses a new videochat platform that is only compatible with Firefox and Chrome. They are both awesome browsers and you can download them for free at 
      %a{href:"http://www.mozilla.org", target:"_blank" } http://www.mozilla.org
      or
      %a{href:"http://www.google.com/chrome", target:"_blank" } http://www.google.com/chrome

    %br

    %h2.large-header For users 

    %h3.question-header I need help. What do I do?

    %p.text 
      Soon, our website will allow to search for experts yourself, but until then:

      %ul.text
        %li 
          Please email us at
          %a{href:"mailto:questions@lorious.com"} questions@lorious.com
          and tell us what you need help with.
        %li We&#39;ll do our best to find you some experts who can help you and send you an email with the list. We&#39;ll include as much as we can about the experts&#39; qualifications and what they charge, so you can pick the expert that&#39;s best for you.
        %li Let us know who you&#39;d like to speak with and some times you&#39;d be available to talk. We&#39;ll work with both of you to schedule an appointment. 
        %li We&#39;ll send you both a link to the videochat half an hour before your scheduled call.


    %h3.question-header Is it free to get help?

    %p.text
      It depends on which expert you speak to. Lorious lets experts set their own rates, so some experts may be willing to help for free while other experts will want to charge for their time. 

    %p.text
      When we provide you a list of experts for your request, we&#39;ll do our best to include as much information about their qualifications as possible so you can pick the expert that&#39;s best for you. 


    %h3.question-header Do I need an appointment to talk to an expert?

    %p.text
      We hope to have an instant videochat function set up soon, but for now, you do need an appointment to talk to an expert. When you send us a request, let us know what date the conversation needs to happen by, and we&#39;ll do our best to facilitate your request.

    %h3.question-header How do I access my video session?

    %p.text
      We&#39;ll send you a link to your video session half an hour before your appointment starts. All you have to do is click the link at the appointed time.

    %h3.question-header How do I know how much to pay?

    %p.text
      Paid conversations start at a minimum of $5 (Free conversations are always free).

    %p.text
      For paid conversations, you&#39;ll owe whatever the expert&#39;s hourly rate is times the amount of time you spoke to them, provided that you hit the $5 mark. If you only talked for 15 minutes, you only pay for 15 minutes.  

    %p.text
      We don&#39;t have the technology in place yet to record the length of your videochat, so we&#39;ll ask both you and the expert to input the conversation length once your videochat is over. If there are any discrepancies, we&#39;ll follow up with both of you to make sure we charge a fair rate. 

    %h3.question-header What if I&#39;m not happy with my conversation?

    %p.text
      We want to make sure all our users get the help that they came for. First, if you realize that your expert isn&#39;t right for you, you can end the conversation within the first 5 minutes and reschedule with someone else, free of charge. However, if you do finish the conversation and still aren&#39;t satisfied for any reason, please let us know at 
      %a{href:"mailto:questions@lorious.com"} questions@lorious.com
      and we&#39;ll give you your money back. 

    %br

    %h2.large-header For experts

    %h3.question-header Why should I be an expert at Lorious?

    %p.text
      At Lorious, we believe that everyone has something to offer. You&#39;ve gathered years of expertise and experience - whether it&#39;s from a professional context or just from practicing something that you love. We want to make it easy for people to share their passion, skills and expertise with the world and help you make a little money while you do it.

    %p.text
      As an expert, you can use Lorious to:

      %ul.text
        %li Share what you know with the world
        %li Help others work through some of the same problems you may have had
        %li Access a wider audience and grow your credibility on the web
        %li Make some money while you do all that


    %h3.question-header Can anyone become an expert?

    %p.text
      We think everybody has the power to help somebody. That&#39;s why we don&#39;t require any specific qualifications, education, or certifications for someone to sign up as an expert.  However, the more background you provide about your skills and expertise, the better we can match you with people who need your help. 

    %p.text
      That said, we want to make sure our users have the best possible experience and get all the answers that they&#39;re looking for.  If an expert receives more than one negative review or complaint from a user, we&#39;ll have to investigate and take appropriate action, which could result in an account suspension.


    %h3.question-header How do I become an expert?

    %p.text
      Soon, you&#39;ll be able to register and fill out your own profile, but for now, just let us know what you&#39;re great at! Email 
      %a{href:"mailto:questions@lorious.com"} questions@lorious.com
      with some details about what you know and what your skills are, and we&#39;ll add you to our expert database. If you could also send us any links to your blog/Etsy store/Twitter/pictures of things you&#39;ve made, that would be even better! The more you tell us about your skills, the better we can match you with people who need your help.


    %h3.question-header Does Lorious let me set my own rates?

    %p.text
      At Lorious, we value your time - so we want you to set rates that you&#39;re comfortable with. Whether you want to help others for free or charge for your time, we want to give you that freedom. 

    %p.text
      If you&#39;re not sure what you should be charging, email
      %a{href:"mailto:questions@lorious.com"} questions@lorious.com
      and we can give you some guidelines and help you figure it out. 


    %h3.question-header Does Lorious charge you to be an expert?

    %p.text
      There are no upfront costs and no monthly membership fees. Lorious only gets paid when you do. Lorious takes a 20% flat commission once the money is transferred to you. 3-10% of that is to cover our credit card fees (depending on the length of the conversation), the rest goes toward building Lorious so that it&#39;s an even better place for our community.

    %h3.question-header How do I start helping people?

    %p.text
      %ol.text
        %li Tell people that you&#39;re available on Lorious. If you make your own appointment, let us know when your appointment is and who you&#39;re speaking to and we&#39;ll send you both a videochat link. 

        %li Wait for us to contact you. We&#39;ll send you an email when we get a request from someone we think you could help. If you&#39;d like to help them, let us know and tell us some times you would be free to talk. We&#39;ll send the user a list of all the available experts and let them choose who they want to speak to. Once they choose, we&#39;ll help both parties schedule an appointment and send you both a link to the videochat half an hour before your scheduled call.

    %p.text
      The more information you give us about your expertise, the better we&#39;ll be able to send you users who need your help.

    %h3.question-header How do I get paid?

    %p.text
      Once we receive the money from your conversation, we&#39;ll transfer your fees to your PayPal account.

    %p.text
      We don&#39;t have the technology in place yet to record the length of your videochat, so we&#39;ll ask both you and the user to input the conversation length once your videochat is over. If there are any discrepancies, we&#39;ll follow up with both of you to make sure we charge a fair rate. 

    %h3.question-header If I&#39;m an expert, can I hire other experts that interest me as well?

    %p.text Of course! We want Lorious to be a learning community for everyone, where everyone (including experts) can use it to access the expertise they need. 

app/views/home/index.html.haml
%h3
  [Lorious Logo] <Main index> - not shown to users
  .pull-right Need advice? Talk to an expert today.
%br 
%br 
%br 
.row
  .span8
    How it works
    %p 1
    %p 2
    %p 3
  .span4
    .well
      = simple_form_for(@users, :html => { :class => 'form-horizontal' }) do |f|
        = f.error_notification

        .form-inputs.row
          = f.input :name, wrapper_html: { }
          = f.input :email, wrapper_html: { }

app/views/home/landing_page.html.haml
/javascript for validation
:javascript
  $(document).ready(function(){
  $('#signup').validate({
      rules: {
          fname: "required",
          email: "email",
      
      },
      messages: {
          fname: "Your name is required",
          email: "Your email is required",
      },
      errorContainer: $('#errorContainer'),
      errorLabelContainer: $('#errorContainer ul'),
      wrapper: 'li'
  });
    });

%section.row-fluid.landing-upper-nav
  .span6.logo
    %a{href: "/"}
      =image_tag "https://s3.amazonaws.com/lorious/layout/lorious_white.svg", width: "100px"
  .span6.nav
    %ul
      %li= link_to "Be an Expert", expert_path
      %li= mail_to "questions@lorious.com", "Contact Us"

%section.row-fluid.hero.hero-landing-page
  .container-fluid
    .span12
      %h2 Learn from the best
      %p Private lessons and consultations from experienced experts who&#39;ve been through it. Whatever your challenge, we connect you with someone who can teach you what you need to know &#8211; anywhere, anytime.
      %a(href="#help-us-out")
        %span.button Sign up

%section.row-fluid.how-it-works
  .container-fluid
    .span6.landing-left
      %h1 How it works...
      %p Lorious puts you in touch with experts so you can get face-to-face instruction online, tailored to your&nbsp;questions
    .span6.landing-right
      %ul
        %li
          .number
            =image_tag "https://s3.amazonaws.com/lorious/layout/elements/landing_page/1.svg", width: "80px"
          .copy
            %h3 Find the perfect expert
            %p Access our community and find the right person to help you. Fees may vary by expert.
        %li
          .number
            =image_tag "https://s3.amazonaws.com/lorious/layout/elements/landing_page/2.svg", width: "80px"
          .copy
            %h3 Get in touch
            %p Work with someone instantly or schedule a conversation at a convenient time
        %li
          .number
            =image_tag "https://s3.amazonaws.com/lorious/layout/elements/landing_page/3.svg", width: "80px"
          .copy
            %h3 Connect and videochat
            %p Talk for 5 minutes or 5 hours, until you&#39;ve gotten the help you need

%section.row-fluid.help-us-out#help-us-out
  .container-fluid
    .span6.landing-left
      %h1 Request an invitation
      %p We&#39;re currently in private beta mode. Please sign up for an invite. 
      
    .span6.landing-right
      = simple_form_for @profile, url: profiles_pre_path, method: :post, html: {id: "signup"} do |f|
        = f.error_notification

        .form-inputs
          = f.input :fname, label: false, input_html: {placeholder: "Your first name", id: "fname"}
          = f.input :email, label: false, input_html: {placeholder: "Your email", id: "email"}
          = f.input :niche, input_html: {value: @niche}, as: :hidden
          
        = f.button :submit, "Request an Invitation", class: "button"

app/views/home/thanks.html.haml
%h3 thanks