config/routes.rb
Lorious::Application.routes.draw do
  



  resources :transactions


  # basic public routes
  authenticated :user do
    root :to => 'users#dashboard'
  end
  
  get "/users/:id/dashboard" => "users#dashboard", as: "user_dashboard"
  get "/accounts" => "users#manage_payments", as: "manage_payments"
  get "/packages" => "home#credit_packages", as: "credit_packages"

  post "/packages/cart" => "credits#credits_cart", as: "credits_pre"

  post "/packages/card/buy" => "credits#buy_credits", as: "buy_credits"

  root :to => "home#audience_home"
  
  get 'blog_home' => "home#blog_home"
  get 'expert' => 'home#blog_home'
  get 'experts' => 'home#blog_home'
  get 'audience' => 'home#audience_home'
  get 'faq' => 'home#faq'
  get 'legal' => 'home#legal'

  get 'confirmed' => "home#confirmed"
  post 'confirmed' => "home#confirmed"

  resources :reviews
  resources :profiles
  resources :requests
  resources :charges
  resources :customers

  resources :services

  scope '/:user_id' do
    resources :appointments
    get "/appointments/:id/confirm" => "appointments#confirm", as: "confirm_appointment"
    resources :recipients
    resources :cards
    resources :credits
  end

  # devise_for :users #, :controllers => { :registrations => "registrations" } 
  devise_for :users, :controllers => { :registrations => "registrations", :omniauth_callbacks => "users/omniauth_callbacks" }
  resources :users
  devise_scope :user do
    get 'login' => "devise/sessions#new"
    get 'logout' => "devise/sessions#destroy"
    get 'signup' => "devise/registrations#new"
  end

  resources :conversations, only: [:index, :show, :new, :create] do
    member do
      post :reply
      post :trash
      post :untrash
    end
  end

  # chat routes
  get "chat/test" => "chat#test"
  # get 'chat/go/:user_id/:chat_key' => "chat#chat_prep"
  get 'chat/go/:chat_key/' => "chat#scheduled_chat", as: "chat_start"
  # get 'chat/go/:user_id/:chat_key/register' => "users#finish_registration"
  # get 'chat/go/:chat_key/error' => "home#error"
  get 'chat/go/:chat_key/end' => "chat#chat_end"

  # chat listener for determining conversation length
  post 'chat/report_listener' => "chat#report_listener"

  # custom signup routes for waiting list signup
  # put 'finish_pre_registration' => "users#edit_incomplete_registration"
  # post "profiles/pre" => "profiles#create_before_signup"
  # post "profiles/preup" => "profiles#update_before_signup"

  # authenticated :user do
  #  root :to => 'requests#index'
  # end

  # get 'message' => "home#message"
  # get '/:niche' => "home#audience_home"

  # user/profile show and edit routes
  get '/:id' => "users#show", as: "user_page"  
  get '/:id/avatar' => "users#upload_avatar", as: "avatar_page"
  get '/:id/expert' => "users#make_expert", as: "expert_approval"
  get '/:id/message' => "conversations#message", as: "message_user"
  # put '/avatars' => "users#update_avatar"

  


end

app/models/credit.rb
class Credit < ActiveRecord::Base
  attr_accessible :hash_id, :number, :transaction_id, :user_id, :status, :appointment_id

  belongs_to :user
  belongs_to :transaction
  belongs_to :appointment

end

app/controllers/credits_controller.rb
class CreditsController < ApplicationController
  # GET /credits
  # GET /credits.json
  def index
    @credits = current_user.credits.order('credits.created_at DESC').page(params[:page]).per(15)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @credits }
    end
  end

  # GET /credits/1
  # GET /credits/1.json
  def show
    @credit = Credit.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @credit }
    end
  end


  def credits_cart
    unless stripe_card_on_file?(current_user)
      redirect_to new_card_path(id: current_user.id), notice: "There is a problem with your card on file. Please update your information before you proceed."
      return
    end

    @credit = Credit.new
    @credit.attributes = params[:credit]

    @number = @credit.number
    @amount = @number

    if @credit.number.nil?
      redirect_to credit_packages_path
      return
    end

    customer = @customer = Stripe::Customer.retrieve(current_user.stripe_customer_id)

    if current_user.card.nil? || current_user.card.stripe_card_id.nil?
      send_mail("Errors @ Lorious", "admin@lorious.com", "Team", "admin@lorious.com", "Lorious ADMIN | Removed Card Error Reported!", "Error reported\r\n\r\nIt appears that #{current_user.email} / #{current_user.username} / #{current_user.id} was buying #{@credit.number} for $#{@amount * 100} and an error was reported. Please verify this transaction and mark it in the database appropriately.")
      redirect_to new_card_path(id: current_user.id), notice: "There is a problem with your card on file. Please update your information before you proceed."
      return
    end

    card = customer.cards.retrieve(current_user.card.stripe_card_id)


    @card_type = card["type"]
    
    @card_name = card["name"]

    @last4 = card["last4"]
    @card_number = "****"+@last4
    
    @card_exp = card["exp_month"].to_s + " / "+ card["exp_year"].to_s[2,3]

  end

  def buy_credits
    @credit = Credit.new(params[:credit])
    @number = @credit.number
    amount = @number
    user = current_user
    
    transaction = payment(current_user, amount)
    credits = credit_transaction(current_user, @number, transaction, nil)

    respond_to do |format|
      if !transaction.nil? && !credits.nil?
      # receipt
      send_mail("Receipts from Lorious", "admin@lorious.com", user.name, user.email, "Lorious Receipts | Thank you for your purchase", "Thank you for your purchase. Now go start solving your challenges by booking an appointment today!\r\n\r\n#{ENV["location"]}\r\n\r\n-The Lorious Team")

        format.html { redirect_to root_path, notice: 'Credits were successfully purchased.' }
        format.json { render json: @credit, status: :created, location: @credit }
      else
        send_mail("Errors @ Lorious", "admin@lorious.com", "Team", "admin@lorious.com", "Lorious ADMIN | Error In Buying Credits Reported!", "Error reported\r\n\r\nIt appears that #{current_user.email} / #{current_user.username} / #{current_user.id} was buying #{@credit.number} for $#{amount} and an error was reported. Please verify this transaction and mark it in the database appropriately.")
        format.html { redirect_to root_path, notice: 'There was an error in processing your transaction. Please check your credit balance and contact customer support if you have any issues.' }
        format.json { render json: @credit.errors, status: :unprocessable_entity }
      end
    end
  end

  def spend_credits
    # check to ensure credit balance > upcoming credit trans
    # # create negative credit trans and credit line item
    # # 
  end

  # GET /credits/new
  # GET /credits/new.json
  # def new
  #   @number = params[:number]
  #   @credit = Credit.new(number: @number)

  #   respond_to do |format|
  #     format.html # new.html.erb
  #     format.json { render json: @credit }
  #   end
  # end

  # # GET /credits/1/edit
  # def edit
  #   @credit = Credit.find(params[:id])
  # end

  # # POST /credits
  # # POST /credits.json
  # def create
  #   @credit = Credit.new(params[:credit])

  #   respond_to do |format|
  #     if @credit.save
  #       format.html { redirect_to @credit, notice: 'Credit was successfully created.' }
  #       format.json { render json: @credit, status: :created, location: @credit }
  #     else
  #       format.html { render action: "new" }
  #       format.json { render json: @credit.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end

  # # PUT /credits/1
  # # PUT /credits/1.json
  # def update
  #   @credit = Credit.find(params[:id])

  #   respond_to do |format|
  #     if @credit.update_attributes(params[:credit])
  #       format.html { redirect_to @credit, notice: 'Credit was successfully updated.' }
  #       format.json { head :no_content }
  #     else
  #       format.html { render action: "edit" }
  #       format.json { render json: @credit.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end

  # # DELETE /credits/1
  # # DELETE /credits/1.json
  # def destroy
  #   @credit = Credit.find(params[:id])
  #   @credit.destroy

  #   respond_to do |format|
  #     format.html { redirect_to credits_url }
  #     format.json { head :no_content }
  #   end
  # end
end

app/helpers/credits_helper.rb
module CreditsHelper
end

app/views/credits/_form.html.haml
= simple_form_for(@credit) do |f|
  = f.error_notification

  .form-inputs
    = f.input :user_id
    = f.input :number
    = f.input :transaction_id
    = f.input :hash_id

  .form-actions
    = f.button :submit

app/views/credits/credits_cart.html.haml
- content_for :main_content do
  %p.strong
    You are buying
    =@number
    Credits
  %br
  %p.muted
    Your
    =@card_type
    ending in
    =@last4
    will be charged
    ='$' + @amount.to_s + '.00'

    = simple_form_for(@credit, url: buy_credits_path) do |f|
      = f.error_notification

      .form-inputs
        = f.input :user_id, as: :hidden
        = f.input :number, as: :hidden

      .form-actions
        = f.button :submit, "Buy Credits"

app/views/credits/edit.html.haml
%h1 Editing credit

= render 'form'

= link_to 'Show', @credit
\|
= link_to 'Back', credits_path

app/views/credits/index.html.haml
%h2 Credit History

.well
  %table.table
    %thead
      %tr
        %th Date
        %th 
        %th Number
        %th Status
        %th For
        %th{:style => "width: 36px;"}
    %tbody
      -@credits.each do |credit|
        %tr
          %td= credit.created_at.strftime("%m/%d/%y")
          %td
            -if credit.number < 0
              %span.label.label-warning
                %i.icon-minus-sign
            -else
              %span.label.label-success
                %i.icon-plus-sign

          %td
            -if credit.number < 0
              %span.label.label-warning
                %i.icon-asterisk
                =credit.number
            -else
              %span.label.label-success
                %i.icon-asterisk
                =credit.number
          %td= credit.status
          %td
            -if credit.number < 0
              Appointment with
              =credit.appointment.host.name
            -else
              Point Purchase
          %td
=paginate @credits


/ %table.table
/   %tr
/     %th User
/     %th Number
/     %th Transaction
/     %th Hash
/     %th
/     %th
/     %th

/   - @credits.each do |credit|
/     %tr
/       %td= credit.user_id
/       %td= credit.number
/       %td= credit.transaction_id
/       %td= credit.hash
/       / %td= link_to 'Show', credit
/       / %td= link_to 'Edit', edit_credit_path(credit)
/       / %td= link_to 'Destroy', credit, :method => :delete, :data => { :confirm => 'Are you sure?' }

/ %br

/ = link_to 'New Credit', new_credit_path

app/views/credits/new.html.haml
%h1 New credit

= render 'form'

= link_to 'Back', credits_path

app/views/credits/show.html.haml
%p#notice= notice

%p
  %b User:
  = @credit.user_id
%p
  %b Number:
  = @credit.number
%p
  %b Transaction:
  = @credit.transaction_id
%p
  %b Hash:
  = @credit.hash

= link_to 'Edit', edit_credit_path(@credit)
\|
= link_to 'Back', credits_path