config/routes.rb
Lorious::Application.routes.draw do
  



  resources :transactions


  # basic public routes
  authenticated :user do
    root :to => 'users#dashboard'
  end
  
  get "/users/:id/dashboard" => "users#dashboard", as: "user_dashboard"
  get "/accounts" => "users#manage_payments", as: "manage_payments"
  get "/packages" => "home#credit_packages", as: "credit_packages"

  post "/packages/cart" => "credits#credits_cart", as: "credits_pre"

  post "/packages/card/buy" => "credits#buy_credits", as: "buy_credits"

  root :to => "home#audience_home"
  
  get 'blog_home' => "home#blog_home"
  get 'expert' => 'home#blog_home'
  get 'experts' => 'home#blog_home'
  get 'audience' => 'home#audience_home'
  get 'faq' => 'home#faq'
  get 'legal' => 'home#legal'

  get 'confirmed' => "home#confirmed"
  post 'confirmed' => "home#confirmed"

  resources :reviews
  resources :profiles
  resources :requests
  resources :charges
  resources :customers

  resources :services

  scope '/:user_id' do
    resources :appointments
    get "/appointments/:id/confirm" => "appointments#confirm", as: "confirm_appointment"
    resources :recipients
    resources :cards
    resources :credits
  end

  # devise_for :users #, :controllers => { :registrations => "registrations" } 
  devise_for :users, :controllers => { :registrations => "registrations", :omniauth_callbacks => "users/omniauth_callbacks" }
  resources :users
  devise_scope :user do
    get 'login' => "devise/sessions#new"
    get 'logout' => "devise/sessions#destroy"
    get 'signup' => "devise/registrations#new"
  end

  resources :conversations, only: [:index, :show, :new, :create] do
    member do
      post :reply
      post :trash
      post :untrash
    end
  end

  # chat routes
  get "chat/test" => "chat#test"
  # get 'chat/go/:user_id/:chat_key' => "chat#chat_prep"
  get 'chat/go/:chat_key/' => "chat#scheduled_chat", as: "chat_start"
  # get 'chat/go/:user_id/:chat_key/register' => "users#finish_registration"
  # get 'chat/go/:chat_key/error' => "home#error"
  get 'chat/go/:chat_key/end' => "chat#chat_end"

  # chat listener for determining conversation length
  post 'chat/report_listener' => "chat#report_listener"

  # custom signup routes for waiting list signup
  # put 'finish_pre_registration' => "users#edit_incomplete_registration"
  # post "profiles/pre" => "profiles#create_before_signup"
  # post "profiles/preup" => "profiles#update_before_signup"

  # authenticated :user do
  #  root :to => 'requests#index'
  # end

  # get 'message' => "home#message"
  # get '/:niche' => "home#audience_home"

  # user/profile show and edit routes
  get '/:id' => "users#show", as: "user_page"  
  get '/:id/avatar' => "users#upload_avatar", as: "avatar_page"
  get '/:id/expert' => "users#make_expert", as: "expert_approval"
  get '/:id/message' => "conversations#message", as: "message_user"
  # put '/avatars' => "users#update_avatar"

  


end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  # GET /transactions
  # GET /transactions.json
  def index
    @transactions = Transaction.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @transactions }
    end
  end

  # GET /transactions/1
  # GET /transactions/1.json
  def show
    @transaction = Transaction.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @transaction }
    end
  end

  # GET /transactions/new
  # GET /transactions/new.json
  def new
    @transaction = Transaction.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @transaction }
    end
  end

  # GET /transactions/1/edit
  def edit
    @transaction = Transaction.find(params[:id])
  end

  # POST /transactions
  # POST /transactions.json
  def create
    @transaction = Transaction.new(params[:transaction])

    respond_to do |format|
      if @transaction.save
        format.html { redirect_to @transaction, notice: 'Transaction was successfully created.' }
        format.json { render json: @transaction, status: :created, location: @transaction }
      else
        format.html { render action: "new" }
        format.json { render json: @transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /transactions/1
  # PUT /transactions/1.json
  def update
    @transaction = Transaction.find(params[:id])

    respond_to do |format|
      if @transaction.update_attributes(params[:transaction])
        format.html { redirect_to @transaction, notice: 'Transaction was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /transactions/1
  # DELETE /transactions/1.json
  def destroy
    @transaction = Transaction.find(params[:id])
    @transaction.destroy

    respond_to do |format|
      format.html { redirect_to transactions_url }
      format.json { head :no_content }
    end
  end


end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/views/transactions/_form.html.haml
= simple_form_for(@transaction) do |f|
  = f.error_notification

  .form-inputs
    = f.input :user_id
    = f.input :appointment_id
    = f.input :credit_id
    = f.input :stripe_charge_id
    = f.input :type
    = f.input :status

  .form-actions
    = f.button :submit

app/views/transactions/edit.html.haml
%h1 Editing transaction

= render 'form'

= link_to 'Show', @transaction
\|
= link_to 'Back', transactions_path

app/views/transactions/index.html.haml
%h1 Listing transactions

%table
  %tr
    %th User
    %th Appointment
    %th Credit
    %th Stripe charge
    %th Type
    %th Status
    %th
    %th
    %th

  - @transactions.each do |transaction|
    %tr
      %td= transaction.user_id
      %td= transaction.appointment_id
      %td= transaction.credit_id
      %td= transaction.stripe_charge_id
      %td= transaction.type
      %td= transaction.status
      %td= link_to 'Show', transaction
      %td= link_to 'Edit', edit_transaction_path(transaction)
      %td= link_to 'Destroy', transaction, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Transaction', new_transaction_path

app/views/transactions/new.html.haml
%h1 New transaction

= render 'form'

= link_to 'Back', transactions_path

app/views/transactions/show.html.haml
%p#notice= notice

%p
  %b User:
  = @transaction.user_id
%p
  %b Appointment:
  = @transaction.appointment_id
%p
  %b Credit:
  = @transaction.credit_id
%p
  %b Stripe charge:
  = @transaction.stripe_charge_id
%p
  %b Type:
  = @transaction.type
%p
  %b Status:
  = @transaction.status

= link_to 'Edit', edit_transaction_path(@transaction)
\|
= link_to 'Back', transactions_path